version: '3'

services:
  nextjs: 
    build:
      context: ./next
    networks:
      - app-network

  nginx: 
    build: ./nginx
    ports:
      - 80:80
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - app-network

  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi-application
    environment:
      PORT: 8000
    volumes:
      - ./fastapi:/code/app
    ports:
      - '8000:8000'
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge